// Subject Test Data
const subjectTestData = {};

subjectTestData['physics'] = {
  name: 'Physics',
  tests: [
    {
      id: 'physics-1',
      title: 'Test 1: Mechanics & Forces',
      difficulty: 'Medium',
      duration: 30,
      questions: [
        { type: 'mcq', question: 'Which of the following is a vector quantity?', options: ['Speed', 'Distance', 'Displacement', 'Energy'], answer: 2, marks: 1, explanation: 'Displacement has both magnitude and direction, making it a vector. Speed, distance, and energy are scalar quantities.' },
        { type: 'mcq', question: 'Newton\'s First Law of Motion is also known as the law of:', options: ['Acceleration', 'Inertia', 'Action-Reaction', 'Gravitation'], answer: 1, marks: 1, explanation: 'Newton\'s First Law states that an object remains at rest or in uniform motion unless acted upon by an external force — this is the law of inertia.' },
        { type: 'mcq', question: 'The SI unit of force is:', options: ['Joule', 'Watt', 'Newton', 'Pascal'], answer: 2, marks: 1, explanation: 'Force is measured in Newtons (N), where 1 N = 1 kg·m/s².' },
        { type: 'mcq', question: 'What is the acceleration due to gravity near Earth\'s surface?', options: ['8.9 m/s²', '9.8 m/s²', '10.8 m/s²', '9.2 m/s²'], answer: 1, marks: 1, explanation: 'The standard acceleration due to gravity is approximately 9.8 m/s² (often rounded to 10 m/s² for calculations).' },
        { type: 'mcq', question: 'Momentum is calculated as:', options: ['mass × velocity', 'mass ÷ velocity', 'force × time', 'mass × acceleration'], answer: 0, marks: 1, explanation: 'Momentum (p) = mass (m) × velocity (v). It is a vector quantity with units kg·m/s.' },
        { type: 'mcq', question: 'In a perfectly elastic collision:', options: ['Kinetic energy is conserved', 'Momentum is not conserved', 'Both objects stop', 'Only potential energy is conserved'], answer: 0, marks: 1, explanation: 'In a perfectly elastic collision, both momentum and kinetic energy are conserved.' },
        { type: 'mcq', question: 'Work done is defined as:', options: ['Force × distance moved in direction of force', 'Force ÷ distance', 'Mass × gravity', 'Power × time'], answer: 0, marks: 1, explanation: 'Work done (W) = Force (F) × distance (s) moved in the direction of the force. Unit: Joule (J).' },
        { type: 'mcq', question: 'The principle of moments states that for equilibrium:', options: ['Sum of clockwise moments = sum of anticlockwise moments', 'Sum of all forces = mass', 'Sum of forces in one direction only', 'Total moment must be maximum'], answer: 0, marks: 1, explanation: 'For a body in equilibrium, the sum of clockwise moments about any point equals the sum of anticlockwise moments about the same point.' },
        { type: 'short', question: 'Define terminal velocity and explain under what conditions it occurs.', answer: 'Terminal velocity is the constant maximum velocity reached by an object falling through a fluid when the drag force equals the gravitational force, resulting in zero net force and zero acceleration.', marks: 2, explanation: 'Terminal velocity occurs when weight = air resistance. The object stops accelerating and falls at constant speed. It depends on the object\'s shape, mass, and the fluid density.' },
        { type: 'short', question: 'State Newton\'s Second Law of Motion and give its mathematical formula.', answer: 'Newton\'s Second Law states that the acceleration of an object is directly proportional to the net force acting on it and inversely proportional to its mass: F = ma.', marks: 2, explanation: 'F = ma, where F is net force (N), m is mass (kg), and a is acceleration (m/s²). This means a larger force produces greater acceleration, while a larger mass reduces acceleration.' },
        { type: 'short', question: 'Explain the difference between mass and weight.', answer: 'Mass is the amount of matter in an object (scalar, unit: kg) and is constant everywhere. Weight is the gravitational force acting on that mass (vector, unit: N) and varies with gravitational field strength.', marks: 2, explanation: 'Mass is an intrinsic property measured in kilograms. Weight = mass × gravitational field strength (W = mg), so weight changes depending on location (e.g., Earth vs Moon).' },
        { type: 'short', question: 'Describe what is meant by the centre of gravity of an object.', answer: 'The centre of gravity is the point through which the entire weight of an object appears to act, regardless of the object\'s orientation or position.', marks: 2, explanation: 'For regular uniform objects, the centre of gravity is at the geometric centre. For irregular objects, it can be found by plumb line experiments or balancing.' },
        { type: 'essay', question: 'Explain Newton\'s three laws of motion, giving a real-life example for each law and describing how they apply to vehicle safety features. [6]', marks: 6 },
        { type: 'essay', question: 'Describe and explain the energy changes that occur when a ball is thrown vertically upward, reaches maximum height, and falls back down. Include a discussion of energy conservation and the effect of air resistance. [6]', marks: 6 }
      ]
    },
    {
      id: 'physics-2',
      title: 'Test 2: Electricity & Magnetism',
      difficulty: 'Hard',
      duration: 30,
      questions: [
        { type: 'mcq', question: 'Ohm\'s Law states that:', options: ['V = I/R', 'V = IR', 'R = VI', 'I = VR'], answer: 1, marks: 1, explanation: 'Ohm\'s Law: V = IR, where V is potential difference (V), I is current (A), and R is resistance (Ω).' },
        { type: 'mcq', question: 'The unit of electrical resistance is:', options: ['Ampere', 'Volt', 'Ohm', 'Watt'], answer: 2, marks: 1, explanation: 'Resistance is measured in Ohms (Ω), named after Georg Simon Ohm.' },
        { type: 'mcq', question: 'In a series circuit, the total resistance is:', options: ['Less than the smallest resistor', 'Equal to the largest resistor', 'The sum of all resistances', 'The product of all resistances'], answer: 2, marks: 1, explanation: 'In series: R_total = R₁ + R₂ + R₃ + ... The current is the same throughout, and voltages add up.' },
        { type: 'mcq', question: 'Which material is commonly used as a fuse wire?', options: ['Copper', 'Aluminium', 'Tin-lead alloy', 'Gold'], answer: 2, marks: 1, explanation: 'Fuse wires are made from low-melting-point alloys (like tin-lead) so they melt and break the circuit when current exceeds safe levels.' },
        { type: 'mcq', question: 'The direction of the magnetic field around a current-carrying wire is determined by:', options: ['Fleming\'s left-hand rule', 'The right-hand grip rule', 'Lenz\'s Law', 'Ohm\'s Law'], answer: 1, marks: 1, explanation: 'The right-hand grip rule: thumb points in current direction, fingers curl in magnetic field direction.' },
        { type: 'mcq', question: 'Electromagnetic induction occurs when:', options: ['A conductor moves through a magnetic field', 'A battery is connected', 'A switch is opened', 'Static charge builds up'], answer: 0, marks: 1, explanation: 'Electromagnetic induction is the production of an e.m.f. across a conductor when it experiences a changing magnetic field (Faraday\'s Law).' },
        { type: 'mcq', question: 'A transformer works on the principle of:', options: ['Ohm\'s Law', 'Electromagnetic induction', 'Conservation of mass', 'Static electricity'], answer: 1, marks: 1, explanation: 'Transformers use electromagnetic induction: an alternating current in the primary coil creates a changing magnetic field, inducing a voltage in the secondary coil.' },
        { type: 'mcq', question: 'Power in an electrical circuit is calculated as:', options: ['P = IV', 'P = I/V', 'P = V/I', 'P = IR'], answer: 0, marks: 1, explanation: 'Electrical power P = IV (current × voltage). Alternative forms: P = I²R = V²/R. Unit: Watt (W).' },
        { type: 'short', question: 'Explain why the current in a circuit increases when more cells are added in series.', answer: 'Adding cells in series increases the total e.m.f. (voltage) of the circuit. Since I = V/R and resistance remains constant, the current increases proportionally.', marks: 2, explanation: 'Cells in series: total e.m.f. = sum of individual e.m.f.s. Higher voltage across the same resistance means more current flows (Ohm\'s Law).' },
        { type: 'short', question: 'Describe the function of a circuit breaker and how it differs from a fuse.', answer: 'A circuit breaker automatically interrupts excessive current and can be reset after tripping, whereas a fuse contains a wire that melts and must be replaced.', marks: 2, explanation: 'Both protect circuits from overcurrent. Fuses are single-use and cheaper; circuit breakers are reusable, more convenient, and respond faster.' },
        { type: 'short', question: 'State Fleming\'s left-hand rule and what it is used for.', answer: 'Fleming\'s left-hand rule: First finger = Field, seCond finger = Current, thuMb = Motion. It determines the direction of force on a current-carrying conductor in a magnetic field.', marks: 2, explanation: 'Used in electric motors. The thumb points in the direction of motion (force), first finger in field direction (N→S), second finger in current direction (+ve to -ve).' },
        { type: 'short', question: 'Explain why power is transmitted at high voltages in the national grid.', answer: 'High voltage transmission reduces current for the same power (P = IV), which reduces heat loss in cables (P_loss = I²R), improving efficiency.', marks: 2, explanation: 'Since power loss depends on I², reducing current dramatically reduces energy loss. Transformers step up voltage for transmission and step down for safe domestic use.' },
        { type: 'essay', question: 'Describe the structure and operation of an alternating current (a.c.) generator. Explain how the design features determine the output voltage and frequency, and compare it with a d.c. motor. [6]', marks: 6 },
        { type: 'essay', question: 'Explain the principle of the transformer, including why it only works with a.c., the role of the soft iron core, and derive the relationship between primary and secondary coils (Vp/Vs = Np/Ns). Discuss energy losses and how they are minimised. [6]', marks: 6 }
      ]
    },
    {
      id: 'physics-3',
      title: 'Test 3: Waves & Optics',
      difficulty: 'Medium',
      duration: 30,
      questions: [
        { type: 'mcq', question: 'The speed of a wave is given by:', options: ['v = f/λ', 'v = fλ', 'v = λ/f', 'v = f + λ'], answer: 1, marks: 1, explanation: 'Wave equation: v = fλ, where v is wave speed (m/s), f is frequency (Hz), and λ is wavelength (m).' },
        { type: 'mcq', question: 'Which type of wave cannot travel through a vacuum?', options: ['X-rays', 'Radio waves', 'Light waves', 'Sound waves'], answer: 3, marks: 1, explanation: 'Sound waves are mechanical waves requiring a medium. Electromagnetic waves (light, X-rays, radio) can travel through vacuum.' },
        { type: 'mcq', question: 'The angle of incidence equals the angle of reflection. This is the law of:', options: ['Refraction', 'Reflection', 'Diffraction', 'Dispersion'], answer: 1, marks: 1, explanation: 'The law of reflection states that the angle of incidence (i) equals the angle of reflection (r), measured from the normal.' },
        { type: 'mcq', question: 'Refraction occurs because waves change:', options: ['Frequency', 'Speed', 'Amplitude', 'Wavelength only'], answer: 1, marks: 1, explanation: 'Refraction occurs when waves cross a boundary between media of different densities, causing a change in speed and direction (frequency stays constant).' },
        { type: 'mcq', question: 'Total internal reflection occurs when:', options: ['Light travels from less to more dense medium', 'Angle of incidence exceeds critical angle', 'Light is absorbed', 'Wavelength decreases'], answer: 1, marks: 1, explanation: 'Total internal reflection occurs when light travels from a denser to less dense medium and the angle of incidence exceeds the critical angle.' },
        { type: 'mcq', question: 'In a convex lens, parallel rays converge at the:', options: ['Optical centre', 'Focal point', 'Principal axis', 'Centre of curvature'], answer: 1, marks: 1, explanation: 'A convex (converging) lens brings parallel rays to a focus at the focal point on the principal axis.' },
        { type: 'mcq', question: 'The electromagnetic spectrum, in order of increasing wavelength, is:', options: ['Radio, visible, UV, X-ray, gamma', 'Gamma, X-ray, UV, visible, radio', 'Visible, UV, X-ray, gamma, radio', 'Gamma, radio, UV, visible, X-ray'], answer: 1, marks: 1, explanation: 'Order: gamma rays (shortest λ) → X-rays → UV → visible → infrared → microwaves → radio waves (longest λ).' },
        { type: 'mcq', question: 'Diffraction is most noticeable when the gap size is:', options: ['Much larger than wavelength', 'Approximately equal to wavelength', 'Much smaller than wavelength', 'Independent of wavelength'], answer: 1, marks: 1, explanation: 'Diffraction effects are greatest when the obstacle or gap size is comparable to the wavelength of the wave.' },
        { type: 'short', question: 'Distinguish between transverse and longitudinal waves, giving one example of each.', answer: 'Transverse waves have oscillations perpendicular to wave direction (e.g., light, water waves). Longitudinal waves have oscillations parallel to wave direction (e.g., sound).', marks: 2, explanation: 'In transverse waves: crests and troughs. In longitudinal waves: compressions and rarefactions. All electromagnetic waves are transverse; sound is longitudinal.' },
        { type: 'short', question: 'Explain what is meant by the critical angle in relation to total internal reflection.', answer: 'The critical angle is the minimum angle of incidence in a denser medium at which light is refracted along the boundary; above this angle, total internal reflection occurs.', marks: 2, explanation: 'Critical angle θc = sin⁻¹(n₂/n₁) where n₁ > n₂. It depends on the refractive indices of the two media.' },
        { type: 'short', question: 'State two uses of fibre optic cables and explain the role of total internal reflection.', answer: 'Uses: telecommunications (high-speed data) and endoscopy (medical imaging). Light is trapped inside the core by total internal reflection at the core-cladding boundary.', marks: 2, explanation: 'Fibre optics use thin glass/plastic fibres. The core has higher refractive index than cladding, so light undergoes repeated total internal reflection with minimal signal loss.' },
        { type: 'short', question: 'Describe how the eye forms an image on the retina and how the lens accommodates for near and distant objects.', answer: 'Light is refracted by the cornea and lens to form a real, inverted image on the retina. The ciliary muscles change lens shape: thicker for near objects, thinner for distant objects.', marks: 2, explanation: 'Accommodation: ciliary muscles contract → suspensory ligaments slacken → lens becomes more convex (near vision). Relaxation produces a flatter lens for distant vision.' },
        { type: 'essay', question: 'Explain the wave-particle duality of light, describing the photoelectric effect and Young\'s double-slit experiment as evidence. Discuss how these observations led to the quantum theory of light. [6]', marks: 6 },
        { type: 'essay', question: 'Describe the structure and function of the human eye, explaining how lenses correct long-sightedness (hyperopia) and short-sightedness (myopia). Include ray diagrams in your explanation. [6]', marks: 6 }
      ]
    }
  ]
};

subjectTestData['chemistry'] = {
  name: 'Chemistry',
  tests: [
    {
      id: 'chemistry-1',
      title: 'Test 1: Atomic Structure & Bonding',
      difficulty: 'Medium',
      duration: 30,
      questions: [
        { type: 'mcq', question: 'The centre of an atom containing protons and neutrons is called the:', options: ['Electron shell', 'Nucleus', 'Orbital', 'Valence band'], answer: 1, marks: 1, explanation: 'The nucleus is the dense central core containing protons (positive) and neutrons (neutral), surrounded by electrons in shells.' },
        { type: 'mcq', question: 'An element has atomic number 17 and mass number 35. How many neutrons does it have?', options: ['17', '18', '35', '52'], answer: 1, marks: 1, explanation: 'Neutrons = mass number - atomic number = 35 - 17 = 18. Protons = 17 (atomic number), electrons = 17 (in neutral atom).' },
        { type: 'mcq', question: 'Isotopes of an element have different numbers of:', options: ['Protons', 'Electrons', 'Neutrons', 'Shells'], answer: 2, marks: 1, explanation: 'Isotopes are atoms of the same element (same proton number) with different numbers of neutrons, hence different mass numbers.' },
        { type: 'mcq', question: 'A covalent bond is formed by:', options: ['Transfer of electrons', 'Sharing of electrons', 'Attraction between ions', 'Delocalised electrons'], answer: 1, marks: 1, explanation: 'Covalent bonding involves the sharing of electron pairs between atoms, typically between non-metals, to achieve stable noble gas configurations.' },
        { type: 'mcq', question: 'Which element has the electron configuration 2,8,8,1?', options: ['Sodium', 'Potassium', 'Calcium', 'Argon'], answer: 1, marks: 1, explanation: 'Potassium (K, atomic number 19) has electron configuration 2,8,8,1. It is in Group 1 with one valence electron.' },
        { type: 'mcq', question: 'Ionic compounds typically have:', options: ['Low melting points', 'High melting points', 'Conduct electricity when solid', 'Are soft and waxy'], answer: 1, marks: 1, explanation: 'Ionic compounds have high melting points due to strong electrostatic forces between oppositely charged ions in a giant lattice.' },
        { type: 'mcq', question: 'Metallic bonding consists of:', options: ['Shared electron pairs', 'Positive ions in a sea of delocalised electrons', 'Electrostatic attraction between oppositely charged ions', 'Weak intermolecular forces'], answer: 1, marks: 1, explanation: 'Metallic bonding: positive metal ions are arranged in a lattice surrounded by a \'sea\' of delocalised valence electrons.' },
        { type: 'mcq', question: 'A double covalent bond is found in:', options: ['Methane (CH₄)', 'Water (H₂O)', 'Oxygen (O₂)', 'Hydrogen (H₂)'], answer: 2, marks: 1, explanation: 'O₂ has a double covalent bond (O=O) with two shared electron pairs. N₂ has a triple bond.' },
        { type: 'short', question: 'Explain why noble gases are unreactive.', answer: 'Noble gases have full outer electron shells (octet/duplet), which is a stable configuration. They have no tendency to gain, lose, or share electrons.', marks: 2, explanation: 'Helium has 2 electrons (duplet); others have 8 (octet). This stable configuration means noble gases do not need to form bonds and are chemically inert.' },
        { type: 'short', question: 'Describe the difference between ionic and covalent bonding.', answer: 'Ionic bonding involves transfer of electrons from metal to non-metal, forming oppositely charged ions. Covalent bonding involves sharing electrons, usually between non-metals.', marks: 2, explanation: 'Ionic: electrostatic attraction between cations and anions (e.g., NaCl). Covalent: shared electron pairs (e.g., H₂O, CO₂). Ionic compounds form giant lattices; covalent can be simple molecules or giant structures.' },
        { type: 'short', question: 'Draw the dot-and-cross diagram for hydrogen chloride (HCl) and identify the type of bonding.', answer: 'HCl has covalent bonding: hydrogen shares one electron with chlorine. Chlorine has 3 lone pairs and 1 shared pair. H–Cl single covalent bond.', marks: 2, explanation: 'Hydrogen (1 electron) shares with chlorine (7 electrons). The shared pair forms a single covalent bond. Chlorine retains 3 lone pairs.' },
        { type: 'short', question: 'State and explain the trends in atomic radius across a period and down a group in the Periodic Table.', answer: 'Across a period: radius decreases due to increasing nuclear charge pulling electrons closer. Down a group: radius increases due to additional electron shells.', marks: 2, explanation: 'Across period: protons increase but shielding stays similar → stronger attraction. Down group: more shells → outer electrons further from nucleus despite increased protons.' },
        { type: 'essay', question: 'Describe the development of atomic models from Dalton to Rutherford to Bohr, explaining the experimental evidence that led to each revision. Include the significance of the Geiger-Marsden experiment. [6]', marks: 6 },
        { type: 'essay', question: 'Explain the properties of giant covalent structures (diamond and graphite) in terms of their bonding and structure. Compare their hardness, electrical conductivity, and melting points, and relate these to their uses. [6]', marks: 6 }
      ]
    },
    {
      id: 'chemistry-2',
      title: 'Test 2: Chemical Reactions & Stoichiometry',
      difficulty: 'Hard',
      duration: 30,
      questions: [
        { type: 'mcq', question: 'The relative formula mass of H₂SO₄ is:', options: ['82', '96', '98', '100'], answer: 2, marks: 1, explanation: 'H₂SO₄ = (2×1) + 32 + (4×16) = 2 + 32 + 64 = 98 g/mol.' },
        { type: 'mcq', question: 'In the reaction: 2H₂ + O₂ → 2H₂O, what is the mole ratio of hydrogen to oxygen?', options: ['1:1', '2:1', '1:2', '2:2'], answer: 1, marks: 1, explanation: 'The balanced equation shows 2 moles of H₂ react with 1 mole of O₂, giving a 2:1 ratio.' },
        { type: 'mcq', question: 'Which of the following is NOT a redox reaction?', options: ['Rusting of iron', 'Combustion of methane', 'Neutralisation of acid and alkali', 'Displacement of copper by zinc'], answer: 2, marks: 1, explanation: 'Neutralisation (acid + base → salt + water) is not redox — no change in oxidation states. Rusting, combustion, and displacement involve electron transfer.' },
        { type: 'mcq', question: 'A catalyst works by:', options: ['Increasing temperature', 'Lowering activation energy', 'Providing more reactants', 'Changing equilibrium position'], answer: 1, marks: 1, explanation: 'Catalysts increase reaction rate by providing an alternative pathway with lower activation energy, without being consumed.' },
        { type: 'mcq', question: 'At equilibrium in a reversible reaction:', options: ['Reactants have fully converted', 'Forward and reverse rates are equal', 'Concentrations are zero', 'Reaction has stopped'], answer: 1, marks: 1, explanation: 'Dynamic equilibrium: forward and reverse reaction rates are equal, concentrations remain constant, but reactions continue at molecular level.' },
        { type: 'mcq', question: 'The pH of a neutral solution at 25°C is:', options: ['0', '7', '14', '1'], answer: 1, marks: 1, explanation: 'pH 7 is neutral at 25°C. pH < 7 acidic, pH > 7 alkaline. pH = -log[H⁺].' },
        { type: 'mcq', question: 'An exothermic reaction is one in which:', options: ['Heat is absorbed', 'Heat is released', 'No energy change occurs', 'Temperature decreases'], answer: 1, marks: 1, explanation: 'Exothermic: energy/heat is released to surroundings (ΔH negative). Examples: combustion, neutralisation.' },
        { type: 'mcq', question: 'The empirical formula of a compound is:', options: ['The actual number of atoms', 'The simplest whole number ratio', 'The molecular mass', 'The structural arrangement'], answer: 1, marks: 1, explanation: 'Empirical formula shows the simplest whole number ratio of atoms. Molecular formula shows actual numbers (e.g., CH₂O empirical, C₆H₁₂O₆ molecular for glucose).' },
        { type: 'short', question: 'Calculate the mass of calcium carbonate (CaCO₃) needed to produce 11 g of CO₂. (Mᵣ: CaCO₃ = 100, CO₂ = 44)', answer: 'Moles of CO₂ = 11/44 = 0.25 mol. From equation CaCO₃ → CaO + CO₂, mole ratio is 1:1. Mass CaCO₃ = 0.25 × 100 = 25 g.', marks: 2, explanation: 'Decomposition: CaCO₃ → CaO + CO₂. 1 mole CaCO₃ produces 1 mole CO₂. 0.25 mol CO₂ requires 0.25 mol CaCO₃ = 25 g.' },
        { type: 'short', question: 'Explain Le Chatelier\'s Principle and apply it to the Haber process for ammonia synthesis.', answer: 'Le Chatelier\'s Principle states that if a system at equilibrium is disturbed, it shifts to counteract the change. In the Haber process, high pressure favours ammonia (fewer gas molecules), and moderate temperature balances rate and yield.', marks: 2, explanation: 'N₂ + 3H₂ ⇌ 2NH₃ (exothermic). High pressure → shifts right (4 → 2 moles). Lower temperature favours products but slows rate; compromise ~450°C with iron catalyst.' },
        { type: 'short', question: 'Distinguish between oxidation and reduction in terms of electrons and oxidation states.', answer: 'Oxidation is loss of electrons/increase in oxidation state. Reduction is gain of electrons/decrease in oxidation state. (OIL RIG)', marks: 2, explanation: 'OIL RIG: Oxidation Is Loss, Reduction Is Gain. Oxidation state increases for oxidation, decreases for reduction. These always occur together in redox reactions.' },
        { type: 'short', question: 'Describe how to calculate percentage yield and explain why actual yield is usually less than theoretical yield.', answer: 'Percentage yield = (actual yield / theoretical yield) × 100%. Actual yield is lower due to incomplete reactions, side reactions, product loss during transfer, or reversible reactions.', marks: 2, explanation: 'Theoretical yield assumes 100% conversion. In practice, losses occur at every stage. Percentage yield measures reaction efficiency.' },
        { type: 'essay', question: 'Describe the Contact Process for manufacturing sulfuric acid, including the key reactions, conditions (temperature, pressure, catalyst), and how they are optimised using Le Chatelier\'s Principle. Include equations and explain the importance of sulfuric acid in industry. [6]', marks: 6 },
        { type: 'essay', question: 'Explain the electrolysis of molten sodium chloride and aqueous copper(II) sulfate. Include half-equations at each electrode, identification of products, and explanations of how concentration affects the products in aqueous electrolysis. [6]', marks: 6 }
      ]
    },
    {
      id: 'chemistry-3',
      title: 'Test 3: Organic Chemistry',
      difficulty: 'Medium',
      duration: 30,
      questions: [
        { type: 'mcq', question: 'The general formula for alkanes is:', options: ['CₙH₂ₙ', 'CₙH₂ₙ₊₂', 'CₙH₂ₙ₋₂', 'CₙHₙ'], answer: 1, marks: 1, explanation: 'Alkanes are saturated hydrocarbons with general formula CₙH₂ₙ₊₂ (e.g., methane CH₄, ethane C₂H₆).' },
        { type: 'mcq', question: 'Which functional group characterises alcohols?', options: ['–COOH', '–OH', '–CHO', '–NH₂'], answer: 1, marks: 1, explanation: 'Alcohols contain the hydroxyl (-OH) functional group attached to a carbon chain (e.g., ethanol C₂H₅OH).' },
        { type: 'mcq', question: 'The product of adding bromine to ethene is:', options: ['Ethane', 'Bromoethane', '1,2-dibromoethane', 'Ethanol'], answer: 2, marks: 1, explanation: 'Ethene (unsaturated) undergoes addition: C₂H₄ + Br₂ → C₂H₄Br₂ (1,2-dibromoethane). Bromine water decolourises.' },
        { type: 'mcq', question: 'Which process converts alkenes to alkanes?', options: ['Combustion', 'Hydrogenation', 'Oxidation', 'Polymerisation'], answer: 1, marks: 1, explanation: 'Hydrogenation adds hydrogen across the double bond in presence of a nickel catalyst: alkene + H₂ → alkane.' },
        { type: 'mcq', question: 'Carboxylic acids react with carbonates to produce:', options: ['Hydrogen gas', 'Salt + water + carbon dioxide', 'Ester + water', 'Alkane + water'], answer: 1, marks: 1, explanation: 'Acid + carbonate → salt + water + CO₂. Example: 2CH₃COOH + Na₂CO₃ → 2CH₃COONa + H₂O + CO₂.' },
        { type: 'mcq', question: 'The polymer formed from ethene is:', options: ['PVC', 'Polyethene (polyethylene)', 'Polystyrene', 'Teflon'], answer: 1, marks: 1, explanation: 'Ethene undergoes addition polymerisation to form polyethene (polyethylene), a widely used plastic.' },
        { type: 'mcq', question: 'Which test distinguishes aldehydes from ketones?', options: ['Bromine water test', 'Fehling\'s solution/Benedict\'s test', 'Litmus test', 'Flame test'], answer: 1, marks: 1, explanation: 'Aldehydes reduce Fehling\'s/Benedict\'s solution (blue → red precipitate). Ketones do not react (unless alpha-hydroxy).' },
        { type: 'mcq', question: 'Esters are formed by the reaction of:', options: ['Acid + alcohol', 'Acid + base', 'Alcohol + alkene', 'Acid + metal'], answer: 0, marks: 1, explanation: 'Esterification: carboxylic acid + alcohol ⇌ ester + water, catalysed by concentrated sulfuric acid.' },
        { type: 'short', question: 'Explain what is meant by a homologous series and give two characteristics.', answer: 'A homologous series is a family of compounds with the same functional group, similar chemical properties, and successive members differing by CH₂. They show gradual physical property trends.', marks: 2, explanation: 'Examples: alkanes, alkenes, alcohols. Characteristics: same general formula, same functional group, similar chemical properties, physical properties change gradually.' },
        { type: 'short', question: 'Write the balanced equation for complete combustion of propane (C₃H₈) and name the products.', answer: 'C₃H₈ + 5O₂ → 3CO₂ + 4H₂O. Products: carbon dioxide and water.', marks: 2, explanation: 'Complete combustion of hydrocarbons produces CO₂ and H₂O. Incomplete combustion produces CO (toxic) and/or carbon (soot).' },
        { type: 'short', question: 'Describe the mechanism of fractional distillation of crude oil and explain how it separates components.', answer: 'Crude oil is heated and vaporised. The vapour enters a fractionating column (hot at bottom, cool at top). Fractions condense at different heights based on boiling points.', marks: 2, explanation: 'Larger molecules with higher boiling points condense lower down. Smaller molecules rise higher before condensing. Produces fractions: bitumen, fuel oil, diesel, kerosene, petrol, LPG.' },
        { type: 'short', question: 'Explain why unsaturated hydrocarbons decolourise bromine water while saturated hydrocarbons do not.', answer: 'Unsaturated hydrocarbons (alkenes) have C=C double bonds that undergo addition reactions with bromine. Saturated hydrocarbons (alkanes) only have C-C single bonds and cannot add bromine.', marks: 2, explanation: 'Bromine test: orange bromine water decolourises with alkenes (addition across double bond) but remains orange with alkanes (no reaction without UV light for substitution).' },
        { type: 'essay', question: 'Describe the reactions of alcohols (combustion, oxidation to carboxylic acids, dehydration to alkenes, and esterification). Include reagents, conditions, and equations for each reaction using ethanol as an example. [6]', marks: 6 },
        { type: 'essay', question: 'Explain the environmental impacts of burning fossil fuels and plastic disposal. Discuss the importance of recycling, biodegradable plastics, and alternative energy sources in reducing these impacts. [6]', marks: 6 }
      ]
    }
  ]
};

subjectTestData['biology'] = {
  name: 'Biology',
  tests: [
    {
      id: 'biology-1',
      title: 'Test 1: Cell Biology & Transport',
      difficulty: 'Medium',
      duration: 30,
      questions: [
        { type: 'mcq', question: 'Which organelle is responsible for protein synthesis?', options: ['Nucleus', 'Mitochondrion', 'Ribosome', 'Golgi apparatus'], answer: 2, marks: 1, explanation: 'Ribosomes are the sites of protein synthesis, translating mRNA into polypeptide chains. Found free in cytoplasm or bound to rough ER.' },
        { type: 'mcq', question: 'The cell membrane is described as fluid mosaic because:', options: ['It is rigid and fixed', 'Phospholipids and proteins can move within the bilayer', 'It contains only phospholipids', 'It is made of cellulose'], answer: 1, marks: 1, explanation: 'The fluid mosaic model describes a phospholipid bilayer with embedded proteins that can move laterally, giving fluidity and mosaic appearance.' },
        { type: 'mcq', question: 'Diffusion is defined as the net movement of particles from:', options: ['Low to high concentration', 'High to low concentration', 'Against a concentration gradient', 'Through a partially permeable membrane'], answer: 1, marks: 1, explanation: 'Diffusion is the passive net movement of particles from a region of higher concentration to lower concentration down a concentration gradient.' },
        { type: 'mcq', question: 'Osmosis specifically refers to the diffusion of:', options: ['Any solute', 'Water molecules', 'Gases', 'Ions'], answer: 1, marks: 1, explanation: 'Osmosis is the net movement of water molecules from a dilute to concentrated solution through a partially permeable membrane.' },
        { type: 'mcq', question: 'Active transport requires:', options: ['Only a concentration gradient', 'ATP and carrier proteins', 'No energy input', 'Large pore channels only'], answer: 1, marks: 1, explanation: 'Active transport moves substances against their concentration gradient, requiring metabolic energy (ATP) and specific carrier proteins.' },
        { type: 'mcq', question: 'Which structure is found in plant cells but NOT animal cells?', options: ['Mitochondria', 'Nucleus', 'Chloroplast', 'Ribosomes'], answer: 2, marks: 1, explanation: 'Chloroplasts contain chlorophyll for photosynthesis and are found only in plant cells (and some algae). Other options are found in both.' },
        { type: 'mcq', question: 'The powerhouse of the cell is the:', options: ['Nucleus', 'Ribosome', 'Mitochondrion', 'Lysosome'], answer: 2, marks: 1, explanation: 'Mitochondria carry out aerobic respiration, producing ATP (energy currency). They have a double membrane and their own DNA.' },
        { type: 'mcq', question: 'Which microscope has the highest resolution?', options: ['Light microscope', 'Transmission electron microscope (TEM)', 'Stereo microscope', 'Dissecting microscope'], answer: 1, marks: 1, explanation: 'TEM uses electron beams instead of light, achieving much higher magnification and resolution (sub-nanometre scale) than light microscopes.' },
        { type: 'short', question: 'Describe the structure of a phospholipid and explain how phospholipids are arranged in the cell membrane.', answer: 'A phospholipid has a hydrophilic phosphate head and two hydrophobic fatty acid tails. In membranes, they form a bilayer with heads facing aqueous environments and tails sandwiched inside.', marks: 2, explanation: 'This arrangement creates a barrier to most water-soluble substances. The hydrophobic core allows lipid-soluble molecules to pass while restricting ions and polar molecules.' },
        { type: 'short', question: 'Explain what happens to a red blood cell placed in distilled water and why.', answer: 'The cell swells and bursts (haemolysis) because distilled water is hypotonic. Water enters by osmosis down the water potential gradient.', marks: 2, explanation: 'Red blood cells have lower water potential than distilled water. Water enters by osmosis, causing the cell to swell. Animal cells lack cell walls so they burst.' },
        { type: 'short', question: 'State two differences between prokaryotic and eukaryotic cells.', answer: 'Prokaryotes lack a membrane-bound nucleus (have nucleoid), no membrane-bound organelles, and have 70S ribosomes. Eukaryotes have a true nucleus, organelles, and 80S ribosomes.', marks: 2, explanation: 'Prokaryotes (bacteria, archaea) are simpler, smaller, and lack mitochondria, ER, Golgi. Eukaryotes (plants, animals, fungi, protists) are more complex with compartmentalised organelles.' },
        { type: 'short', question: 'Describe the role of the nucleus in a eukaryotic cell.', answer: 'The nucleus contains chromosomes (DNA), controls cell activities by regulating gene expression, and is the site of DNA replication and transcription.', marks: 2, explanation: 'The nuclear envelope with pores controls entry/exit. Nucleolus produces ribosomal RNA. DNA carries genetic instructions for protein synthesis and cell division.' },
        { type: 'essay', question: 'Explain the process of mitosis, including the stages (prophase, metaphase, anaphase, telophase) and their significance in growth, repair, and asexual reproduction. Describe how cytokinesis differs in animal and plant cells. [6]', marks: 6 },
        { type: 'essay', question: 'Compare and contrast the processes of diffusion, osmosis, and active transport. Include examples of where each occurs in living organisms, the requirements for each process, and explain how cell structure facilitates these transport mechanisms. [6]', marks: 6 }
      ]
    },
    {
      id: 'biology-2',
      title: 'Test 2: Genetics & Inheritance',
      difficulty: 'Hard',
      duration: 30,
      questions: [
        { type: 'mcq', question: 'DNA replication is described as semi-conservative because:', options: ['Each new DNA has one old and one new strand', 'Both strands are newly synthesised', 'Only half the DNA is copied', 'DNA is destroyed after copying'], answer: 0, marks: 1, explanation: 'In semi-conservative replication, each daughter DNA molecule consists of one parental strand and one newly synthesised complementary strand.' },
        { type: 'mcq', question: 'A heterozygous genotype is:', options: ['AA', 'aa', 'Aa', 'AAA'], answer: 2, marks: 1, explanation: 'Heterozygous means having two different alleles (e.g., Aa). Homozygous dominant = AA, homozygous recessive = aa.' },
        { type: 'mcq', question: 'Which nitrogenous base is found in RNA but NOT in DNA?', options: ['Adenine', 'Thymine', 'Uracil', 'Cytosine'], answer: 2, marks: 1, explanation: 'RNA contains uracil (U) instead of thymine (T). Both contain adenine, guanine, and cytosine.' },
        { type: 'mcq', question: 'The process of protein synthesis where mRNA is decoded to make a protein is called:', options: ['Transcription', 'Replication', 'Translation', 'Mutation'], answer: 2, marks: 1, explanation: 'Translation occurs at ribosomes where tRNA brings amino acids according to mRNA codons, forming a polypeptide chain.' },
        { type: 'mcq', question: 'If a recessive trait appears in offspring, what must be true about the parents?', options: ['Both are homozygous dominant', 'At least one is homozygous recessive', 'Both carry at least one recessive allele', 'Only one parent carries the allele'], answer: 2, marks: 1, explanation: 'Recessive traits (aa) require one recessive allele from each parent. Both parents must be carriers (Aa) or homozygous recessive (aa).' },
        { type: 'mcq', question: 'Crossing over during meiosis occurs between:', options: ['Sister chromatids', 'Non-sister chromatids of homologous chromosomes', 'Any two chromosomes', 'DNA and RNA'], answer: 1, marks: 1, explanation: 'Crossing over occurs between non-sister chromatids of homologous chromosomes during prophase I, creating genetic recombination.' },
        { type: 'mcq', question: 'A mutation is:', options: ['A normal cell division', 'A change in the DNA sequence', 'A type of enzyme', 'A reproductive process'], answer: 1, marks: 1, explanation: 'Mutations are changes in the DNA base sequence. They can be substitutions, insertions, deletions, or chromosomal changes. Some are harmful, neutral, or beneficial.' },
        { type: 'mcq', question: 'In a monohybrid cross between two heterozygotes (Aa × Aa), the phenotypic ratio in offspring is:', options: ['1:1', '3:1', '1:2:1', '9:3:3:1'], answer: 1, marks: 1, explanation: 'Aa × Aa produces genotypic ratio 1 AA : 2 Aa : 1 aa. If A is dominant, phenotypic ratio is 3 dominant : 1 recessive.' },
        { type: 'short', question: 'Describe the structure of DNA, including the bonding between bases.', answer: 'DNA is a double helix of two antiparallel sugar-phosphate strands. Bases pair specifically: A-T (two hydrogen bonds) and G-C (three hydrogen bonds).', marks: 2, explanation: 'Deoxyribose sugar and phosphate form the backbone. Bases project inward. Complementary base pairing ensures faithful replication and transcription.' },
        { type: 'short', question: 'Explain the difference between genotype and phenotype.', answer: 'Genotype is the genetic makeup (alleles present, e.g., Aa). Phenotype is the observable physical or biochemical characteristic resulting from genotype and environment.', marks: 2, explanation: 'Example: genotype Bb (heterozygous) may show brown eyes phenotype if B is dominant. Environment can influence phenotype (e.g., nutrition affecting height).' },
        { type: 'short', question: 'State two sources of genetic variation in sexually reproducing organisms.', answer: 'Crossing over during prophase I of meiosis and independent assortment of homologous chromosomes. Fertilisation also combines genetic material from two parents.', marks: 2, explanation: 'Crossing over exchanges segments between homologous chromosomes. Independent assortment randomises chromosome combinations. Random fertilisation adds further variation.' },
        { type: 'short', question: 'Explain why sex-linked traits like colour blindness are more common in males than females.', answer: 'Males have XY sex chromosomes with only one X. A recessive allele on their single X will be expressed. Females need two copies (XX) to show the trait.', marks: 2, explanation: 'Colour blindness is X-linked recessive. Males: XᵇY = affected. Females: XᵇXᵇ = affected, XᴮXᵇ = carrier. Therefore males are more frequently affected.' },
        { type: 'essay', question: 'Describe the processes of transcription and translation in protein synthesis. Include the role of RNA polymerase, mRNA, tRNA, ribosomes, and codons. Explain how the genetic code is universal, non-overlapping, and degenerate. [6]', marks: 6 },
        { type: 'essay', question: 'Explain Mendel\'s laws of segregation and independent assortment, using genetic crosses (Punnett squares) to illustrate monohybrid and dihybrid inheritance. Discuss why Mendel chose pea plants and how his work established the foundation of genetics. [6]', marks: 6 }
      ]
    },
    {
      id: 'biology-3',
      title: 'Test 3: Human Physiology',
      difficulty: 'Medium',
      duration: 30,
      questions: [
        { type: 'mcq', question: 'Which blood vessel carries oxygenated blood from the lungs to the heart?', options: ['Aorta', 'Vena cava', 'Pulmonary vein', 'Pulmonary artery'], answer: 2, marks: 1, explanation: 'Pulmonary veins carry oxygenated blood from lungs to left atrium. Arteries usually carry oxygenated blood, but pulmonary artery carries deoxygenated blood to lungs.' },
        { type: 'mcq', question: 'The primary site of gas exchange in the lungs is the:', options: ['Bronchus', 'Trachea', 'Alveolus', 'Bronchiole'], answer: 2, marks: 1, explanation: 'Alveoli are tiny air sacs with thin walls (one cell thick), large surface area, and rich blood supply — ideal for rapid gas exchange.' },
        { type: 'mcq', question: 'Which enzyme breaks down starch in the human digestive system?', options: ['Pepsin', 'Amylase', 'Lipase', 'Trypsin'], answer: 1, marks: 1, explanation: 'Salivary amylase (mouth) and pancreatic amylase (small intestine) hydrolyse starch to maltose. Pepsin digests protein; lipase digests fats.' },
        { type: 'mcq', question: 'The functional unit of the kidney is the:', options: ['Neuron', 'Nephron', 'Alveolus', 'Villus'], answer: 1, marks: 1, explanation: 'The nephron filters blood, reabsorbs useful substances, and produces urine. Each kidney contains about one million nephrons.' },
        { type: 'mcq', question: 'Insulin is produced by which cells in the pancreas?', options: ['Alpha cells', 'Beta cells', 'Delta cells', 'Acinar cells'], answer: 1, marks: 1, explanation: 'Beta cells in the Islets of Langerhans produce insulin, which lowers blood glucose by promoting cellular uptake and glycogen formation.' },
        { type: 'mcq', question: 'Which component of blood is responsible for clotting?', options: ['Red blood cells', 'White blood cells', 'Platelets', 'Plasma'], answer: 2, marks: 1, explanation: 'Platelets (thrombocytes) aggregate at injury sites and release clotting factors. Fibrinogen in plasma forms fibrin mesh to seal wounds.' },
        { type: 'mcq', question: 'During aerobic respiration, where is most ATP produced?', options: ['Cytoplasm', 'Mitochondrial matrix', 'Inner mitochondrial membrane', 'Nucleus'], answer: 2, marks: 1, explanation: 'The electron transport chain on the inner mitochondrial membrane (cristae) produces ~34 ATP via oxidative phosphorylation. Glycolysis produces 2 ATP in cytoplasm.' },
        { type: 'mcq', question: 'Vaccination works by:', options: ['Killing all pathogens in the body', 'Stimulating active immunity and memory cell production', 'Injecting antibodies directly', 'Suppressing the immune system'], answer: 1, marks: 1, explanation: 'Vaccines contain weakened/dead pathogens or antigens that stimulate primary immune response, producing memory cells for faster future response.' },
        { type: 'short', question: 'Explain how the structure of red blood cells is adapted for transporting oxygen.', answer: 'Red blood cells have no nucleus (more room for haemoglobin), a biconcave shape (increases surface area), and contain haemoglobin which binds oxygen reversibly.', marks: 2, explanation: 'Biconcave shape increases surface area-to-volume ratio for diffusion. Haemoglobin has high affinity for O₂ in lungs and releases it in tissues. No mitochondria — rely on anaerobic respiration.' },
        { type: 'short', question: 'Describe how the heart functions as a double pump in the circulatory system.', answer: 'The right side pumps deoxygenated blood to the lungs (pulmonary circulation). The left side pumps oxygenated blood to the body (systemic circulation).', marks: 2, explanation: 'Double circulation maintains high pressure in systemic circuit. Right ventricle → pulmonary artery → lungs → pulmonary vein → left atrium → left ventricle → aorta → body.' },
        { type: 'short', question: 'Explain the role of villi in the small intestine.', answer: 'Villi increase surface area for absorption. They contain blood capillaries (absorb amino acids, glucose) and lacteals (absorb fatty acids and glycerol).', marks: 2, explanation: 'Microvilli on epithelial cells further increase surface area. Thin walls (one cell thick), good blood supply, and constant movement enhance efficient nutrient absorption.' },
        { type: 'short', question: 'Distinguish between the nervous and endocrine systems in terms of speed and duration of response.', answer: 'Nervous system: fast, short-lived, targeted responses via electrical impulses. Endocrine system: slower, longer-lasting, widespread responses via hormones in blood.', marks: 2, explanation: 'Nerves use action potentials (milliseconds) with precise targeting. Hormones travel in blood (seconds to minutes), affect multiple targets, and responses persist longer.' },
        { type: 'essay', question: 'Describe the mechanism of breathing (inhalation and exhalation) involving the diaphragm and intercostal muscles. Explain how alveoli are adapted for gas exchange, and describe the transport of oxygen and carbon dioxide in the blood. [6]', marks: 6 },
        { type: 'essay', question: 'Explain how blood glucose concentration is regulated in the human body. Include the roles of insulin, glucagon, the pancreas, and liver. Describe the symptoms and causes of Type 1 and Type 2 diabetes. [6]', marks: 6 }
      ]
    }
  ]
};

