#!/usr/bin/env python3
import os
import re

NOTES_DIR = "/home/node/.openclaw/workspace/LearnAi/notes"

def read_file(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

def write_file(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def join_lines(lines):
    return "\n".join(lines)

def gcse_ec1():
    return join_lines([
        '<div class="notes-section">',
        '<h2>Atomic Structure</h2>',
        '<h3>The Atom</h3>',
        '<p>An atom has a tiny central <strong>nucleus</strong> containing protons and neutrons, surrounded by electrons in energy levels (shells).</p>',
        '<ul>',
        '<li><strong>Proton</strong>: mass = 1, charge = +1</li>',
        '<li><strong>Neutron</strong>: mass = 1, charge = 0</li>',
        '<li><strong>Electron</strong>: mass = 1/1840, charge = -1</li>',
        '</ul>',
        '<div class="formula-box">',
        'Mass Number (A) = protons + neutrons<br>',
        'Atomic Number (Z) = number of protons<br>',
        'Number of neutrons = A - Z',
        '</div>',
        '',
        '<h3>Isotopes</h3>',
        '<p>Isotopes are atoms of the same element with the <strong>same number of protons</strong> but <strong>different numbers of neutrons</strong>.</p>',
        '<div class="formula-box">',
        'Relative Atomic Mass (Ar) = sum(isotope mass x abundance) / 100',
        '</div>',
        '',
        '<h3>Electronic Configuration</h3>',
        '<p>Electrons fill shells from the nucleus outward:</p>',
        '<ul>',
        '<li>1st shell: max 2 electrons</li>',
        '<li>2nd shell: max 8 electrons</li>',
        '<li>3rd shell: max 8 electrons (at GCSE)</li>',
        '</ul>',
        '<p>Example: Sodium (Na, Z=11) = 2.8.1; Chlorine (Cl, Z=17) = 2.8.7</p>',
        '',
        '<h3>Ions</h3>',
        '<p>Metals lose electrons to form <strong>positive ions (cations)</strong>. Non-metals gain electrons to form <strong>negative ions (anions)</strong>.</p>',
        '<div class="highlight-box">',
        '<h4>Exam Tip</h4>',
        '<p>Group number = number of outer-shell electrons for Groups 1-2 and 6-7. The charge on the ion equals the number of electrons gained or lost.</p>',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>The Periodic Table</h2>',
        '<h3>Group 1 - Alkali Metals</h3>',
        '<ul>',
        '<li>Very reactive metals; react vigorously with water</li>',
        '<li>Reactivity <strong>increases</strong> down the group</li>',
        '<li>Form +1 ions; produce alkaline solutions</li>',
        '</ul>',
        '',
        '<h3>Group 7 - Halogens</h3>',
        '<ul>',
        '<li>Reactive non-metals; exist as diatomic molecules (F2, Cl2, Br2, I2)</li>',
        '<li>Reactivity <strong>decreases</strong> down the group</li>',
        '<li>Form -1 ions; undergo displacement reactions</li>',
        '</ul>',
        '<div class="formula-box">',
        'Cl2(aq) + 2NaBr(aq) -&gt; 2NaCl(aq) + Br2(aq)',
        '</div>',
        '',
        '<h3>Group 0 - Noble Gases</h3>',
        '<ul>',
        '<li>Monatomic, colourless, odourless gases</li>',
        '<li>Full outer shell, very unreactive</li>',
        '<li>Used in lighting (neon), as inert atmospheres (argon)</li>',
        '</ul>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<div class="summary-box">',
        '<h2>Quick Recap</h2>',
        '<ul>',
        '<li>Protons = atomic number; neutrons = mass number - atomic number</li>',
        '<li>Isotopes have same proton number, different neutron number</li>',
        '<li>Electron shells fill 2, 8, 8 at GCSE level</li>',
        '<li>Group 1 reactivity increases down the group; Group 7 decreases</li>',
        '<li>More reactive halogen displaces less reactive halogen from its salt</li>',
        '<li>Noble gases have full outer shells and are unreactive</li>',
        '</ul>',
        '</div>',
        '<div class="exam-tips">',
        '<h2>Exam Tips</h2>',
        '<ul>',
        '<li>Always state the number of protons, neutrons, and electrons clearly</li>',
        '<li>When explaining reactivity trends, mention <strong>both</strong> distance from nucleus AND shielding</li>',
        '<li>In displacement reactions, identify the halogen correctly by colour changes</li>',
        '<li>Remember: Cl2 displaces Br- and I-; Br2 displaces I- only</li>',
        '</ul>',
        '</div>',
        '</div>',
    ])

def gcse_ec2():
    return join_lines([
        '<div class="notes-section">',
        '<h2>Ionic Bonding</h2>',
        '<h3>Formation</h3>',
        '<p>Ionic bonding occurs by the <strong>transfer of electrons</strong> from a metal atom to a non-metal atom, producing oppositely charged ions.</p>',
        '<div class="formula-box">',
        'Na -&gt; Na+ + e-<br>',
        'Cl + e- -&gt; Cl-<br>',
        'Na+ + Cl- -&gt; NaCl',
        '</div>',
        '',
        '<h3>Properties of Ionic Compounds</h3>',
        '<ul>',
        '<li>High melting and boiling points (strong electrostatic attraction)</li>',
        '<li>Soluble in water</li>',
        '<li>Conduct electricity when molten or in aqueous solution</li>',
        '<li>Do NOT conduct when solid (ions are fixed in lattice)</li>',
        '<li>Form giant ionic lattice structures</li>',
        '</ul>',
        '<div class="highlight-box">',
        '<h4>Exam Tip</h4>',
        '<p>Always use the phrase <strong>strong electrostatic attraction between oppositely charged ions</strong>.</p>',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Covalent Bonding</h2>',
        '<h3>Simple Molecular Substances</h3>',
        '<p>Small molecules held together by covalent bonds within the molecule, but weak intermolecular forces between molecules.</p>',
        '<ul>',
        '<li>Low melting/boiling points (weak intermolecular forces)</li>',
        '<li>Do not conduct electricity</li>',
        '<li>Often gases or liquids at room temperature</li>',
        '</ul>',
        '<p>Examples: H2O, CO2, O2, NH3</p>',
        '',
        '<h3>Giant Covalent Structures</h3>',
        '<ul>',
        '<li><strong>Diamond</strong>: each carbon bonded to 4 others; very hard; high melting point; does not conduct</li>',
        '<li><strong>Graphite</strong>: each carbon bonded to 3 others in layers; layers slide (soft); conducts electricity (delocalised electrons between layers)</li>',
        '<li><strong>Graphene</strong>: single layer of graphite; very strong; excellent conductor</li>',
        '</ul>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Metallic Bonding</h2>',
        '<p>Metallic bonding is the electrostatic attraction between <strong>positive metal ions</strong> and a <strong>sea of delocalised electrons</strong>.</p>',
        '<ul>',
        '<li>High melting/boiling points</li>',
        '<li>Conduct electricity (delocalised electrons are free to move)</li>',
        '<li>Malleable and ductile (layers of ions can slide over each other)</li>',
        '</ul>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<div class="summary-box">',
        '<h2>Quick Recap</h2>',
        '<ul>',
        '<li>Ionic = electron transfer, giant lattice, high mp, conduct when molten/aqueous</li>',
        '<li>Covalent = electron sharing, simple molecular (low mp) OR giant covalent (high mp)</li>',
        '<li>Metallic = positive ions + sea of electrons, conduct, malleable, high mp</li>',
        '<li>Diamond: 4 bonds per C, hard, non-conductor</li>',
        '<li>Graphite: 3 bonds per C, layers slide, conducts (delocalised e-)</li>',
        '</ul>',
        '</div>',
        '<div class="exam-tips">',
        '<h2>Exam Tips</h2>',
        '<ul>',
        '<li>Always mention <strong>electrostatic attraction</strong> for ionic and metallic bonding</li>',
        '<li>Distinguish between <strong>bond strength</strong> (covalent) and <strong>intermolecular forces</strong> (simple molecular)</li>',
        '<li>Graphite conducts because of <strong>delocalised electrons between layers</strong></li>',
        '<li>Do not say ionic compounds "melt easily" - they have high melting points!</li>',
        '</ul>',
        '</div>',
        '</div>',
    ])

def gcse_ec3():
    return join_lines([
        '<div class="notes-section">',
        '<h2>Acids, Bases and Indicators</h2>',
        '<h3>Definitions</h3>',
        '<ul>',
        '<li><strong>Acid</strong>: substance that donates H+ ions in solution; pH &lt; 7</li>',
        '<li><strong>Base</strong>: substance that neutralises an acid</li>',
        '<li><strong>Alkali</strong>: a soluble base; produces OH- ions in solution; pH &gt; 7</li>',
        '</ul>',
        '',
        '<h3>pH Scale</h3>',
        '<ul>',
        '<li>pH 0-3: strong acid</li>',
        '<li>pH 4-6: weak acid</li>',
        '<li>pH 7: neutral</li>',
        '<li>pH 8-10: weak alkali</li>',
        '<li>pH 11-14: strong alkali</li>',
        '</ul>',
        '',
        '<h3>Universal Indicator Colours</h3>',
        '<ul>',
        '<li>Red, orange, yellow (acidic)</li>',
        '<li>Green (neutral)</li>',
        '<li>Blue, purple (alkaline)</li>',
        '</ul>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Neutralisation Reactions</h2>',
        '<p>Acid + Base -&gt; Salt + Water</p>',
        '<div class="formula-box">',
        'H+(aq) + OH-(aq) -&gt; H2O(l)',
        '</div>',
        '',
        '<h3>Preparing Soluble Salts</h3>',
        '<p>Add excess insoluble base to warm dilute acid. Filter to remove excess base. Heat filtrate to evaporate some water, then allow to crystallise.</p>',
        '',
        '<h3>Preparing Insoluble Salts</h3>',
        '<p>Mix solutions containing the required ions. Filter, wash with distilled water, and dry.</p>',
        '<div class="formula-box">',
        'Pb(NO3)2(aq) + 2NaCl(aq) -&gt; PbCl2(s) + 2NaNO3(aq)',
        '</div>',
        '',
        '<h3>Titration</h3>',
        '<div class="formula-box">',
        'moles = concentration (mol/dm3) x volume (dm3)<br>',
        '1 dm3 = 1000 cm3',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<div class="summary-box">',
        '<h2>Quick Recap</h2>',
        '<ul>',
        '<li>Acid + Base -&gt; Salt + Water (neutralisation)</li>',
        '<li>H+ + OH- -&gt; H2O is the ionic equation</li>',
        '<li>Soluble salts: acid + excess insoluble base -&gt; filter -&gt; crystallise</li>',
        '<li>Insoluble salts: precipitation by mixing two solutions</li>',
        '<li>Titration gives accurate volumes for neutralisation</li>',
        '<li>Naming: metal name + acid root (chloride, sulfate, nitrate)</li>',
        '</ul>',
        '</div>',
        '<div class="exam-tips">',
        '<h2>Exam Tips</h2>',
        '<ul>',
        '<li>Always convert cm3 to dm3 by dividing by 1000 in titration calculations</li>',
        '<li>State the indicator colour change clearly (e.g. "pink to colourless")</li>',
        '<li>When preparing soluble salts, excess base is used to ensure all acid reacts</li>',
        '<li>Precipitation reactions always have a solid product</li>',
        '</ul>',
        '</div>',
        '</div>',
    ])

def gcse_ec5():
    return join_lines([
        '<div class="notes-section">',
        '<h2>Introduction to Organic Chemistry</h2>',
        '<h3>Carbon - The Key Element</h3>',
        '<p>Carbon forms the basis of organic chemistry because it can form <strong>four covalent bonds</strong>, allowing chains, rings, and branches.</p>',
        '',
        '<h3>Homologous Series</h3>',
        '<p>A homologous series is a family of compounds with:</p>',
        '<ul>',
        '<li>The same <strong>functional group</strong></li>',
        '<li>The same <strong>general formula</strong></li>',
        '<li>Similar <strong>chemical properties</strong></li>',
        '<li>Gradual change in <strong>physical properties</strong></li>',
        '</ul>',
        '',
        '<h3>Key Homologous Series at GCSE</h3>',
        '<table style="width:100%;border-collapse:collapse;margin:16px 0;">',
        '<tr style="background:var(--light);"><th style="padding:8px;border:1px solid #ddd;">Series</th><th style="padding:8px;border:1px solid #ddd;">Functional Group</th><th style="padding:8px;border:1px solid #ddd;">General Formula</th></tr>',
        '<tr><td style="padding:8px;border:1px solid #ddd;">Alkanes</td><td style="padding:8px;border:1px solid #ddd;">C-C single bonds only</td><td style="padding:8px;border:1px solid #ddd;">CnH2n+2</td></tr>',
        '<tr><td style="padding:8px;border:1px solid #ddd;">Alkenes</td><td style="padding:8px;border:1px solid #ddd;">C=C double bond</td><td style="padding:8px;border:1px solid #ddd;">CnH2n</td></tr>',
        '<tr><td style="padding:8px;border:1px solid #ddd;">Alcohols</td><td style="padding:8px;border:1px solid #ddd;">-OH</td><td style="padding:8px;border:1px solid #ddd;">CnH2n+1OH</td></tr>',
        '<tr><td style="padding:8px;border:1px solid #ddd;">Carboxylic acids</td><td style="padding:8px;border:1px solid #ddd;">-COOH</td><td style="padding:8px;border:1px solid #ddd;">CnH2n+1COOH</td></tr>',
        '</table>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Alkanes</h2>',
        '<p>Saturated hydrocarbons containing only C-C single bonds.</p>',
        '<div class="formula-box">',
        'Complete combustion: CH4 + 2O2 -&gt; CO2 + 2H2O<br>',
        'Incomplete combustion: 2CH4 + 3O2 -&gt; 2CO + 4H2O',
        '</div>',
        '<p>Cracking breaks long alkane chains into shorter alkanes and alkenes.</p>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Alkenes</h2>',
        '<p>Unsaturated hydrocarbons with a C=C double bond. They undergo <strong>addition reactions</strong>.</p>',
        '',
        '<h3>Bromine Water Test</h3>',
        '<p>Alkenes decolourise orange bromine water. Alkanes do not.</p>',
        '<div class="formula-box">',
        'C2H4 + Br2 -&gt; C2H4Br2',
        '</div>',
        '',
        '<h3>Addition Polymerisation</h3>',
        '<div class="formula-box">',
        'n C2H4 -&gt; -(CH2-CH2)n-  (poly(ethene))',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Alcohols</h2>',
        '<p>Alcohols contain the -OH functional group. Ethanol (C2H5OH) is the most common.</p>',
        '<ul>',
        '<li>Produced by fermentation of sugars with yeast (aq, 30-40C, anaerobic)</li>',
        '<li>Can be oxidised to ethanoic acid</li>',
        '<li>Used as fuels, solvents, and in alcoholic drinks</li>',
        '</ul>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<div class="summary-box">',
        '<h2>Quick Recap</h2>',
        '<ul>',
        '<li>Alkanes: saturated, C-C only, CnH2n+2</li>',
        '<li>Alkenes: unsaturated, C=C, CnH2n, decolourise bromine water</li>',
        '<li>Alcohols: -OH group, produced by fermentation</li>',
        '<li>Carboxylic acids: -COOH, weak acids</li>',
        '<li>Addition polymerisation: many monomers -&gt; one polymer</li>',
        '<li>Cracking: large alkanes -&gt; smaller alkanes + alkenes</li>',
        '</ul>',
        '</div>',
        '<div class="exam-tips">',
        '<h2>Exam Tips</h2>',
        '<ul>',
        '<li>When drawing polymers, show the repeating unit with bonds extending through brackets</li>',
        '<li>Bromine water test distinguishes alkanes (no change) from alkenes (turns colourless)</li>',
        '<li>Fermentation requires yeast, warm temperature, and absence of oxygen</li>',
        '</ul>',
        '</div>',
        '</div>',
    ])

def gcse_ec6():
    return join_lines([
        '<div class="notes-section">',
        '<h2>Exothermic and Endothermic Reactions</h2>',
        '<h3>Energy Changes</h3>',
        '<ul>',
        '<li><strong>Exothermic</strong>: energy is released to the surroundings; deltaH is negative</li>',
        '<li><strong>Endothermic</strong>: energy is taken in from the surroundings; deltaH is positive</li>',
        '</ul>',
        '',
        '<h3>Examples</h3>',
        '<ul>',
        '<li>Exothermic: combustion, neutralisation, many oxidation reactions</li>',
        '<li>Endothermic: thermal decomposition, photosynthesis, dissolving ammonium nitrate in water</li>',
        '</ul>',
        '<div class="formula-box">',
        'deltaH = H(products) - H(reactants)<br>',
        'Negative deltaH = exothermic<br>',
        'Positive deltaH = endothermic',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Bond Energies</h2>',
        '<p>Energy is required to <strong>break bonds</strong> (endothermic) and released when <strong>bonds form</strong> (exothermic).</p>',
        '<div class="formula-box">',
        'deltaH = sum(bond energies of bonds broken) - sum(bond energies of bonds formed)',
        '</div>',
        '<div class="highlight-box">',
        '<h4>Exam Tip</h4>',
        '<p>Always list all bonds broken and all bonds formed. Do not forget to multiply by the number of each bond type.</p>',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Rate of Reaction</h2>',
        '<h3>Factors Affecting Rate</h3>',
        '<ul>',
        '<li><strong>Concentration</strong>: higher concentration -&gt; more particles per unit volume -&gt; more collisions -&gt; faster rate</li>',
        '<li><strong>Temperature</strong>: higher temperature -&gt; particles have more energy -&gt; more frequent and energetic collisions -&gt; faster rate</li>',
        '<li><strong>Surface area</strong>: larger surface area -&gt; more exposed particles -&gt; more collisions -&gt; faster rate</li>',
        '<li><strong>Catalyst</strong>: provides alternative pathway with lower activation energy -&gt; faster rate without being used up</li>',
        '</ul>',
        '',
        '<h3>Collision Theory</h3>',
        '<p>For a reaction to occur, particles must:</p>',
        '<ol>',
        '<li>Collide with each other</li>',
        '<li>Have sufficient energy (at least activation energy)</li>',
        '<li>Have the correct orientation</li>',
        '</ol>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<div class="summary-box">',
        '<h2>Quick Recap</h2>',
        '<ul>',
        '<li>Exothermic: gives out heat, deltaH negative, products lower energy than reactants</li>',
        '<li>Endothermic: takes in heat, deltaH positive, products higher energy than reactants</li>',
        '<li>deltaH = bonds broken - bonds formed</li>',
        '<li>Rate increases with: higher concentration, higher temperature, greater surface area, catalyst</li>',
        '<li>Catalysts are not used up in the reaction</li>',
        '</ul>',
        '</div>',
        '<div class="exam-tips">',
        '<h2>Exam Tips</h2>',
        '<ul>',
        '<li>When drawing energy level diagrams, label activation energy and deltaH clearly</li>',
        '<li>For bond energy calculations, show your working - list every bond</li>',
        '<li>Collision theory requires <strong>three</strong> conditions: collision, sufficient energy, correct orientation</li>',
        '<li>A catalyst lowers activation energy; it does NOT change deltaH or yield</li>',
        '</ul>',
        '</div>',
        '</div>',
    ])

def gcse_ec7():
    return join_lines([
        '<div class="notes-section">',
        '<h2>Reversible Reactions and Equilibrium</h2>',
        '<h3>Dynamic Equilibrium</h3>',
        '<p>In a reversible reaction at equilibrium in a <strong>closed system</strong>:</p>',
        '<ul>',
        '<li>The rate of the forward reaction equals the rate of the reverse reaction</li>',
        '<li>The concentrations of reactants and products remain constant</li>',
        '<li>Both forward and reverse reactions are still occurring</li>',
        '</ul>',
        '<div class="formula-box">',
        'N2(g) + 3H2(g) &lt;=&gt; 2NH3(g)',
        '</div>',
        '',
        '<h3>Le Chatelier Principle</h3>',
        '<p>If a dynamic equilibrium is disturbed, the system adjusts to <strong>oppose the change</strong>.</p>',
        '<ul>',
        '<li><strong>Increase temperature</strong>: equilibrium shifts in the endothermic direction</li>',
        '<li><strong>Increase pressure</strong>: equilibrium shifts towards the side with fewer gas molecules</li>',
        '<li><strong>Increase concentration</strong>: equilibrium shifts to remove the added substance</li>',
        '<li><strong>Catalyst</strong>: speeds up both forward and reverse reactions equally; no shift</li>',
        '</ul>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>The Haber Process</h2>',
        '<p>Industrial production of ammonia:</p>',
        '<div class="formula-box">',
        'N2(g) + 3H2(g) &lt;=&gt; 2NH3(g)    deltaH = -92 kJ/mol',
        '</div>',
        '<ul>',
        '<li><strong>Pressure</strong>: 150-250 atm (high pressure favours product side)</li>',
        '<li><strong>Temperature</strong>: 450C (compromise: lower T favours exothermic forward reaction but is too slow)</li>',
        '<li><strong>Catalyst</strong>: iron</li>',
        '<li>Unreacted N2 and H2 are recycled</li>',
        '</ul>',
        '<div class="highlight-box">',
        '<h4>Exam Tip</h4>',
        '<p>The Haber process uses a compromise temperature: 450C is a balance between rate (favoured by high T) and yield (favoured by low T).</p>',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Redox Reactions</h2>',
        '<p><strong>Oxidation</strong> is loss of electrons; <strong>reduction</strong> is gain of electrons. (OIL RIG)</p>',
        '<div class="formula-box">',
        'CuO + H2 -&gt; Cu + H2O<br>',
        'CuO is reduced (loses oxygen); H2 is oxidised (gains oxygen)',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<div class="summary-box">',
        '<h2>Quick Recap</h2>',
        '<ul>',
        '<li>Dynamic equilibrium: forward rate = reverse rate, concentrations constant, closed system</li>',
        '<li>Le Chatelier: system opposes changes in temperature, pressure, concentration</li>',
        '<li>Higher T shifts towards endothermic side; higher P shifts towards fewer gas molecules</li>',
        '<li>Haber process: N2 + 3H2 &lt;=&gt; 2NH3; 450C, 150-250 atm, iron catalyst</li>',
        '<li>OIL RIG: Oxidation Is Loss, Reduction Is Gain (of electrons)</li>',
        '</ul>',
        '</div>',
        '<div class="exam-tips">',
        '<h2>Exam Tips</h2>',
        '<ul>',
        '<li>Always state "in a closed system" when describing equilibrium</li>',
        '<li>When applying Le Chatelier, clearly state the direction of shift AND justify it</li>',
        '<li>For Haber process, explain WHY 450C is a compromise temperature</li>',
        '<li>In redox, identify both oxidation and reduction half-equations separately</li>',
        '</ul>',
        '</div>',
        '</div>',
    ])

def gcse_ec8():
    return join_lines([
        '<div class="notes-section">',
        '<h2>Electrolysis</h2>',
        '<h3>Principles</h3>',
        '<p>Electrolysis is the decomposition of an ionic compound using <strong>direct current electricity</strong>.</p>',
        '<ul>',
        '<li><strong>Cathode (negative)</strong>: reduction occurs; positive ions (cations) gain electrons</li>',
        '<li><strong>Anode (positive)</strong>: oxidation occurs; negative ions (anions) lose electrons</li>',
        '</ul>',
        '<div class="formula-box">',
        'At cathode: Cu2+ + 2e- -&gt; Cu<br>',
        'At anode: 2Cl- -&gt; Cl2 + 2e-',
        '</div>',
        '',
        '<h3>Molten Electrolysis</h3>',
        '<ul>',
        '<li>Molten NaCl -&gt; Na at cathode, Cl2 at anode</li>',
        '<li>Molten PbBr2 -&gt; Pb at cathode, Br2 at anode</li>',
        '</ul>',
        '',
        '<h3>Aqueous Electrolysis</h3>',
        '<ul>',
        '<li>At cathode: if metal is more reactive than hydrogen, H2 is produced instead of the metal</li>',
        '<li>At anode: if halide ions are present, halogen is produced; otherwise O2 is produced from water</li>',
        '</ul>',
        '<div class="highlight-box">',
        '<h4>Exam Tip</h4>',
        '<p>Remember the reactivity series: if the metal is above hydrogen, H2 is produced at the cathode.</p>',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Electrolysis of Aluminium Oxide</h2>',
        '<ul>',
        '<li>Electrolyte: molten Al2O3 dissolved in cryolite (Na3AlF6) to lower melting point</li>',
        '<li>Cathode: molten aluminium forms at the bottom</li>',
        '<li>Anode: oxygen is produced; reacts with carbon anodes to form CO2</li>',
        '</ul>',
        '<div class="formula-box">',
        'At cathode: Al3+ + 3e- -&gt; Al<br>',
        'At anode: 2O2- -&gt; O2 + 4e-',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Fuel Cells</h2>',
        '<p>A hydrogen-oxygen fuel cell produces electricity directly from chemical reactions:</p>',
        '<div class="formula-box">',
        '2H2(g) + O2(g) -&gt; 2H2O(l)',
        '</div>',
        '<ul>',
        '<li>Advantages: only product is water (clean), more efficient than combustion engines</li>',
        '<li>Disadvantages: hydrogen is difficult to store and transport safely</li>',
        '</ul>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<div class="summary-box">',
        '<h2>Quick Recap</h2>',
        '<ul>',
        '<li>Electrolysis decomposes ionic compounds using DC electricity</li>',
        '<li>Cathode = negative = reduction = cations gain electrons</li>',
        '<li>Anode = positive = oxidation = anions lose electrons</li>',
        '<li>Molten: only compound ions present; aqueous: water competes</li>',
        '<li>Aluminium extraction uses cryolite to lower melting point</li>',
        '<li>Fuel cells: H2 + O2 -&gt; H2O; clean but hydrogen storage is challenging</li>',
        '</ul>',
        '</div>',
        '<div class="exam-tips">',
        '<h2>Exam Tips</h2>',
        '<ul>',
        '<li>Always write half-equations with electrons (e-) on the correct side</li>',
        '<li>For aqueous electrolysis, use the reactivity series to predict products at the cathode</li>',
        '<li>At the anode: halides -&gt; halogen; no halide -&gt; oxygen from water</li>',
        '<li>Remember cryolite purpose: lowers melting point AND saves energy</li>',
        '</ul>',
        '</div>',
        '</div>',
    ])

def ial_ec1():
    return join_lines([
        '<div class="notes-section">',
        '<h2>Atomic Structure</h2>',
        '<h3>Fundamental Particles</h3>',
        '<ul>',
        '<li><strong>Proton</strong>: relative charge +1, relative mass 1, located in nucleus</li>',
        '<li><strong>Neutron</strong>: relative charge 0, relative mass 1, located in nucleus</li>',
        '<li><strong>Electron</strong>: relative charge -1, relative mass 1/1840, located in orbitals</li>',
        '</ul>',
        '<div class="formula-box">',
        'Mass Number (A) = protons + neutrons<br>',
        'Atomic Number (Z) = number of protons<br>',
        'Isotopes: same Z, different A',
        '</div>',
        '',
        '<h3>Electronic Configuration and Orbitals</h3>',
        '<p>Electrons occupy orbitals within subshells:</p>',
        '<ul>',
        '<li><strong>s orbital</strong>: spherical, holds 2 electrons</li>',
        '<li><strong>p orbitals</strong>: 3 dumbbell orbitals (px, py, pz), hold 6 electrons total</li>',
        '<li><strong>d orbitals</strong>: 5 orbitals, hold 10 electrons total</li>',
        '</ul>',
        '<div class="formula-box">',
        'Filling order: 1s -&gt; 2s -&gt; 2p -&gt; 3s -&gt; 3p -&gt; 4s -&gt; 3d -&gt; 4p -&gt; 5s -&gt; 4d -&gt; 5p -&gt; 6s -&gt; 4f -&gt; 5d -&gt; 6p',
        '</div>',
        '',
        '<h3>Rules for Filling Orbitals</h3>',
        '<ul>',
        '<li><strong>Aufbau principle</strong>: fill lowest energy orbitals first</li>',
        '<li><strong>Pauli exclusion principle</strong>: max 2 electrons per orbital with opposite spins</li>',
        '<li><strong>Hund rule</strong>: electrons occupy degenerate orbitals singly before pairing</li>',
        '</ul>',
        '<p>Exceptions: Cr = [Ar] 3d5 4s1 and Cu = [Ar] 3d10 4s1</p>',
        '',
        '<h3>Ionisation Energy</h3>',
        '<p><strong>First ionisation energy</strong>: energy required to remove one mole of electrons from one mole of gaseous atoms.</p>',
        '<div class="formula-box">',
        'X(g) -&gt; X+(g) + e-',
        '</div>',
        '<p>Factors affecting IE:</p>',
        '<ul>',
        '<li><strong>Nuclear charge</strong>: higher -&gt; higher IE</li>',
        '<li><strong>Atomic radius</strong>: larger -&gt; lower IE</li>',
        '<li><strong>Shielding</strong>: more inner electrons -&gt; lower IE</li>',
        '</ul>',
        '<p>Trends:</p>',
        '<ul>',
        '<li>Across a period: IE increases</li>',
        '<li>Down a group: IE decreases</li>',
        '<li>Exceptions: Group 2 to 3 and Group 5 to 6</li>',
        '</ul>',
        '',
        '<h3>Successive Ionisation Energies</h3>',
        '<p>Large jumps in successive IE values indicate removal of an electron from a new, inner shell.</p>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Periodicity</h2>',
        '<h3>Trends Across Period 3</h3>',
        '<ul>',
        '<li><strong>Atomic radius</strong>: decreases across period</li>',
        '<li><strong>Ionisation energy</strong>: generally increases</li>',
        '<li><strong>Electronegativity</strong>: increases across period</li>',
        '<li><strong>Melting point</strong>: peaks at Group 14 (giant covalent Si)</li>',
        '</ul>',
        '',
        '<h3>Trends Down Group 2</h3>',
        '<ul>',
        '<li>Atomic radius increases, IE decreases, reactivity increases</li>',
        '</ul>',
        '',
        '<h3>Trends Down Group 7 (Halogens)</h3>',
        '<ul>',
        '<li>Atomic radius increases, IE decreases, electronegativity decreases</li>',
        '<li>Reactivity decreases down the group</li>',
        '</ul>',
        '<div class="formula-box">',
        'Cl2(aq) + 2NaBr(aq) -&gt; 2NaCl(aq) + Br2(aq)',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Mass Spectrometry</h2>',
        '<p>Used to determine relative atomic/molecular masses and identify compounds.</p>',
        '<ul>',
        '<li><strong>Molecular ion peak (M+)</strong>: m/z = relative molecular mass</li>',
        '<li><strong>Fragmentation peaks</strong>: characteristic fragments help identify structure</li>',
        '</ul>',
        '<div class="formula-box">',
        'Common fragments: CH3+ (m/z 15), CH2=OH+ (m/z 31), CH3CO+ (m/z 43), COOH+ (m/z 45), C6H5+ (m/z 77)',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<div class="summary-box">',
        '<h2>Quick Recap</h2>',
        '<ul>',
        '<li>Orbital filling: 1s 2s 2p 3s 3p 4s 3d 4p...</li>',
        '<li>Cr = [Ar] 3d5 4s1; Cu = [Ar] 3d10 4s1</li>',
        '<li>IE increases across period, decreases down group</li>',
        '<li>Exceptions at G2 to G3 and G5 to G6</li>',
        '<li>Successive IE jumps reveal shell structure</li>',
        '<li>Mass spec: M+ = Mr; fragmentation identifies structure</li>',
        '</ul>',
        '</div>',
        '<div class="exam-tips">',
        '<h2>Exam Tips</h2>',
        '<ul>',
        '<li>Explain IE trends using BOTH nuclear charge and shielding/atomic radius</li>',
        '<li>For exceptions, always specify the orbital being entered</li>',
        '<li>In mass spec, state that molecular ion peak gives Mr, not the base peak</li>',
        '</ul>',
        '</div>',
        '</div>',
    ])


def ial_ec2():
    return join_lines([
        '<div class="notes-section">',
        '<h2>Ionic Bonding and Lattice Energy</h2>',
        '<h3>Formation</h3>',
        '<p>Ionic bonding is the electrostatic attraction between oppositely charged ions in a giant ionic lattice.</p>',
        '<div class="formula-box">',
        'Lattice Energy (deltaH_latt) = enthalpy change when 1 mole of ionic solid is formed from gaseous ions',
        '</div>',
        '',
        '<h3>Factors Affecting Lattice Energy</h3>',
        '<ul>',
        '<li><strong>Ionic charge</strong>: higher charges -&gt; stronger attraction</li>',
        '<li><strong>Ionic radius</strong>: smaller ions -&gt; ions closer together -&gt; stronger attraction</li>',
        '</ul>',
        '<div class="formula-box">',
        'Lattice energy proportional to (q+ x q-) / (r+ + r-)',
        '</div>',
        '',
        '<h3>Born-Haber Cycles</h3>',
        '<div class="formula-box">',
        'deltaHf = deltaH_atom + deltaH_ion + deltaH_ea + deltaH_latt',
        '</div>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Covalent Bonding</h2>',
        '<h3>Bond Polarity</h3>',
        '<p>Covalent bonds are polar when there is a significant electronegativity difference between bonded atoms.</p>',
        '',
        '<h3>Shapes of Molecules (VSEPR Theory)</h3>',
        '<table style="width:100%;border-collapse:collapse;margin:16px 0;">',
        '<tr style="background:var(--light);"><th style="padding:8px;border:1px solid #ddd;">Electron Pairs</th><th style="padding:8px;border:1px solid #ddd;">Bond Pairs</th><th style="padding:8px;border:1px solid #ddd;">Lone Pairs</th><th style="padding:8px;border:1px solid #ddd;">Shape</th><th style="padding:8px;border:1px solid #ddd;">Bond Angle</th></tr>',
        '<tr><td style="padding:8px;border:1px solid #ddd;">2</td><td style="padding:8px;border:1px solid #ddd;">2</td><td style="padding:8px;border:1px solid #ddd;">0</td><td style="padding:8px;border:1px solid #ddd;">Linear</td><td style="padding:8px;border:1px solid #ddd;">180 deg</td></tr>',
        '<tr><td style="padding:8px;border:1px solid #ddd;">3</td><td style="padding:8px;border:1px solid #ddd;">3</td><td style="padding:8px;border:1px solid #ddd;">0</td><td style="padding:8px;border:1px solid #ddd;">Trigonal planar</td><td style="padding:8px;border:1px solid #ddd;">120 deg</td></tr>',
        '<tr><td style="padding:8px;border:1px solid #ddd;">4</td><td style="padding:8px;border:1px solid #ddd;">4</td><td style="padding:8px;border:1px solid #ddd;">0</td><td style="padding:8px;border:1px solid #ddd;">Tetrahedral</td><td style="padding:8px;border:1px solid #ddd;">109.5 deg</td></tr>',
        '<tr><td style="padding:8px;border:1px solid #ddd;">4</td><td style="padding:8px;border:1px solid #ddd;">3</td><td style="padding:8px;border:1px solid #ddd;">1</td><td style="padding:8px;border:1px solid #ddd;">Pyramidal</td><td style="padding:8px;border:1px solid #ddd;">~107 deg</td></tr>',
        '<tr><td style="padding:8px;border:1px solid #ddd;">4</td><td style="padding:8px;border:1px solid #ddd;">2</td><td style="padding:8px;border:1px solid #ddd;">2</td><td style="padding:8px;border:1px solid #ddd;">Bent</td><td style="padding:8px;border:1px solid #ddd;">~104.5 deg</td></tr>',
        '<tr><td style="padding:8px;border:1px solid #ddd;">6</td><td style="padding:8px;border:1px solid #ddd;">6</td><td style="padding:8px;border:1px solid #ddd;">0</td><td style="padding:8px;border:1px solid #ddd;">Octahedral</td><td style="padding:8px;border:1px solid #ddd;">90 deg</td></tr>',
        '</table>',
        '<p>Lone pairs repel more strongly than bonding pairs, reducing bond angles.</p>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<h2>Intermolecular Forces</h2>',
        '<ul>',
        '<li><strong>London dispersion forces</strong>: temporary dipoles in all molecules</li>',
        '<li><strong>Dipole-dipole forces</strong>: permanent dipoles in polar molecules</li>',
        '<li><strong>Hydrogen bonding</strong>: strong dipole-dipole attraction when H is bonded to N, O, or F</li>',
        '</ul>',
        '<p>Hydrogen bonding explains:</p>',
        '<ul>',
        '<li>High boiling points of H2O, NH3, HF</li>',
        '<li>Ice being less dense than water</li>',
        '<li>High solubility of alcohols and sugars in water</li>',
        '</ul>',
        '</div>',
        '',
        '<div class="notes-section">',
        '<div class="summary-box">',
        '<h2>Quick Recap</h2>',
        '<ul>',
        '<li>Lattice energy proportional to (q+ x q-) / (r+ + r-)</li>',
        '<li>Born-Haber cycles relate enthalpy of formation to lattice energy</li>',
        '<li>VSEPR: electron pairs repel; lone pairs repel more than bonding pairs</li>',
        '<li>London dispersion &lt; dipole-dipole &lt; hydrogen bonding &lt; covalent/ionic bonds</li>',
        '<li>Hydrogen bonding requires H bonded to N, O, or F</li>',
        '</ul>',
        '</div>',
        '<div class="exam-tips">',
        '<h2>Exam Tips</h2>',
        '<ul>',
        '<li>Always explain lattice energy changes in terms of ionic charge AND ionic radius</li>',
        '<li>When predicting shapes, count ALL electron pairs first, then determine lone pairs</li>',
        '<li>State the effect of lone pairs on bond angles explicitly</li>',
        '</ul>',
        '</div>',
        '</div>',
    ])

